# Generated by Django 3.2.5 on 2021-07-15 11:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=django_countries.fields.CountryField(max_length=200),
        ),
    ]
