# Generated by Django 3.2.5 on 2021-07-15 12:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_trip_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=django_countries.fields.CountryField(max_length=200),
        ),
    ]
